//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20161125_EFTxWithSP.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EFTestDBEntities : DbContext
    {
        public EFTestDBEntities()
            : base("name=EFTestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MyOrder> MyOrders { get; set; }
        public virtual DbSet<OrderNoGenerator> OrderNoGenerators { get; set; }
    
        public virtual int usp_get_order_no(ObjectParameter po_order_no)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_get_order_no", po_order_no);
        }
    }
}
